source/hello/urls.py
from django.contrib import admin
from django.urls import path, include

api_urlpatterns = [
    path('v1/', include("api_v1.urls")),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/', include(api_urlpatterns))
]

source/webapp/urls.py
from django.urls import path


from webapp.views import ProductList, ProductView, ProductCreate, ProductUpdate, ProductDelete, CartCreate, CartView, \
     CartDeleteView, CartDeleteOneView, OrderCreateView, OrdersView

app_name = "webapp"

urlpatterns = [
     path('', ProductList.as_view(), name="index"),
     path('product/<int:pk>/', ProductView.as_view(), name="product_view"),
     path('product/add/', ProductCreate.as_view(), name='product_add'),
     path('product/<int:pk>/delete/', ProductDelete.as_view(), name='product_delete'),
     path('product/<int:pk>/update/', ProductUpdate.as_view(), name='product_update'),
     path('product/<int:pk>/add-to-cart/', CartCreate.as_view(), name='product_add_to_cart'),
     path('cart', CartView.as_view(), name='cart_view'),
     path('cart/<int:pk>/delete/', CartDeleteView.as_view(), name='cart_delete_view'),
     path('cart/<int:pk>/delete-one/', CartDeleteOneView.as_view(), name='cart_delete_one_view'),
     path('order/create/', OrderCreateView.as_view(), name='order_create_view'),
     path('orders/', OrdersView.as_view(), name='orders_view')
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from django.db.models import F, ExpressionWrapper as E, Sum
from django.urls import reverse

User = get_user_model()

CATEGORY_CHOICES = [('0', 'other'), ('1', 'smartphone'),  ('2', 'computers')]


class Product(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Product name')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Product description')
    category = models.CharField(max_length=30, default='0', null=False, blank=False, choices=CATEGORY_CHOICES, verbose_name='Category')
    remainder = models.PositiveIntegerField(verbose_name='Remainder')
    price = models.DecimalField(verbose_name='Price', max_digits=7, decimal_places=2)

    def get_absolute_url(self):
        return reverse("webapp:product_view", kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.name} - {self.category} - {self.price}"

    class Meta:
        db_table = 'products'
        verbose_name = 'product'
        verbose_name_plural = 'products'


class Cart(models.Model):
    product = models.ForeignKey("webapp.Product", on_delete=models.CASCADE, related_name="in_cart", verbose_name="Товар в корзине")
    qty = models.PositiveIntegerField(verbose_name='количество товара в корзине', default=1)

    def __str__(self):
        return f'{self.product.name} - {self.qty}'

    @classmethod
    def get_with_total(cls):
        return cls.objects.annotate(total=E(F("qty") * F("product__price"), output_field=models.DecimalField()))

    @classmethod
    def get_with_product(cls):
        return cls.get_with_total().select_related("product")

    @classmethod
    def get_cart_total(cls):
        total = cls.get_with_total().aggregate(cart_total=Sum("total"))
        return total['cart_total']

    class Meta:
        db_table = 'cart'
        verbose_name = 'product in cart'
        verbose_name_plural = 'products in cart'


class Order(models.Model):
    name = models.CharField(max_length=50, verbose_name='Name')
    phone = models.CharField(max_length=30, verbose_name='Phone')
    address = models.CharField(max_length=100, verbose_name='Address')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created")
    products = models.ManyToManyField('webapp.Product', related_name='orders',
                                      verbose_name='products', through='webapp.OrderProduct',
                                      through_fields=['order', 'product'])
    user = models.ForeignKey(User, related_name="orders", on_delete=models.SET_DEFAULT, default=1)

    def __str__(self):
        return f'{self.name} - {self.phone}'

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = 'Orders'


class OrderProduct(models.Model):
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE,
                                verbose_name='Product', related_name='order_products')
    order = models.ForeignKey('webapp.Order', on_delete=models.CASCADE,
                              verbose_name='Order', related_name='order_products')
    qty = models.PositiveIntegerField(verbose_name="quantity")

    def __str__(self):
        return f'{self.product.name} - {self.order.name}'

    class Meta:
        verbose_name = 'Product in order'
        verbose_name_plural = 'products in order'

source/webapp/forms.py
from django import forms
from django.forms import widgets

from webapp.models import Product, Cart, Order


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = "__all__"


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30, required=False, label="Найти")


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ['qty']


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ["products", "user"]

source/webapp/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from webapp.forms import ProductForm
from webapp.models import Product


def index_view(request):
    products = Product.objects.filter(remainder__gte=1).order_by('category', 'name')
    return render(request, "index.html", {'products': products})


def product_view(request, pk):
    product = Product.objects.get(pk=pk)
    return render(request, "product_view.html", {'product': product})


def create_product_view(request):
    if request.method == 'GET':
        form = ProductForm()
        return render(request, 'product_create.html', {"form": form})
    else:
        form = ProductForm(data=request.POST)
        if form.is_valid():
            new_product = form.save()
            return redirect('product_view', pk=new_product.pk)
        return render(request, 'product_create.html', {"form": form})


def product_update_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'GET':
        form = ProductForm(initial={
            'name': product.name,
            'description': product.description,
            'category': product.category,
            'remainder': product.remainder,
            'price': product.price
        })
        return render(request, 'product_update.html', {"product": product, "form": form})
    else:
        form = ProductForm(data=request.POST)
        if form.is_valid():
            product.name = form.cleaned_data.get('name')
            product.description = form.cleaned_data.get('description')
            product.category = form.cleaned_data.get('category')
            product.remainder = form.cleaned_data.get('remainder')
            product.price = form.cleaned_data.get('price')
            product.save()
            return redirect('product_view', pk=product.pk)
        return render(request, 'product_update.html', {"product": product, "form": form})


def product_delete_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'GET':
        return render(request, "product_delete.html", {"product": product})
    else:
        product.delete()
        return redirect("index")

source/webapp/views/base.py
from django.db.models import Q
from django.views.generic import ListView

from webapp.forms import SearchForm


class SearchView(ListView):
    search_form_class = SearchForm
    search_form_field = "search"
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = self.get_query()
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.search_form_class()
        if self.search_value:
            context['form'] = self.search_form_class(initial={self.search_form_field: self.search_value})
            context[self.search_form_field] = self.search_value
        return context

    def get_form(self):
        return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get(self.search_form_field)

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

source/webapp/views/cart_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DeleteView

from webapp.forms import CartForm, OrderForm
from webapp.models import Product, Cart, Order, OrderProduct


class CartCreate(CreateView):
    model = Cart
    form_class = CartForm

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        qty = form.cleaned_data.get('qty', 1)
        # self.request.session['item'] = [{'product': product, 'qty': qty}]
        try:
            cart_product = Cart.objects.get(product=product)
            if cart_product.qty + qty <= product.remainder:
                cart_product.qty += qty
                cart_product.save()
        except Cart.DoesNotExist:
            if qty <= product.remainder:
                Cart.objects.create(product=product, qty=qty)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next = self.request.GET.get("next")
        if next:
            return next
        return reverse("webapp:index")


class CartView(ListView):
    # model = Cart
    template_name = "cart/cart_view.html"
    context_object_name = "cart"

    def get_queryset(self):
        return Cart.get_with_product()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context["total"] = Cart.get_cart_total()
        context["form"] = OrderForm()
        return context


class CartDeleteView(DeleteView):
    model = Cart
    success_url = reverse_lazy("webapp:cart_view")

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class CartDeleteOneView(DeleteView):
    model = Cart
    success_url = reverse_lazy("webapp:cart_view")

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()

        self.object.qty -= 1
        if self.object.qty < 1:
            self.object.delete()
        else:
            self.object.save()
        return HttpResponseRedirect(success_url)


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    success_url = reverse_lazy("webapp:index")

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.user = self.request.user
        response = super().form_valid(form)
        order = self.object

        cart_products = Cart.objects.all()
        products = []
        order_products = []
        for item in cart_products:
            product = item.product
            qty = item.qty
            product.remainder -= qty
            products.append(product)
            order_product = OrderProduct(product=product, qty=qty, order=order)
            order_products.append(order_product)
        OrderProduct.objects.bulk_create(order_products)
        Product.objects.bulk_update(products, ("remainder",))
        cart_products.delete()
        return response


class OrdersView(LoginRequiredMixin, ListView):
    template_name = "cart/order_view.html"
    model = Order
    context_object_name = 'orders'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)

source/webapp/views/product_views.py
# Create your views here.
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProductForm
from webapp.models import Product
from webapp.views.base import SearchView


class ProductList(SearchView):
    model = Product
    template_name = "products/index.html"
    context_object_name = "products"
    paginate_by = 5
    search_fields = ["name__icontains", "description__icontains", "category__icontains"]

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(remainder__gte=1).order_by('category', 'name')


class ProductView(DetailView):
    model = Product
    template_name = "products/product_view.html"


class ProductCreate(PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_create.html'
    permission_required = 'webapp.add_product'


class ProductUpdate(PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/product_update.html'
    permission_required = "webapp.change_product"


class ProductDelete(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = "products/product_delete.html"
    success_url = reverse_lazy('webapp:index')
    permission_required = "webapp.delete_product"

source/webapp/templates/products/index.html
{% extends 'base.html' %}

{% block content %}
    {% include 'partial/simple_search.html' %}
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
<h1>List of products</h1>
    <div class="row my-3">
        {% for product in products %}
            <div class="col-12 col-md-4 col-lg-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title"><a
                                href="{% url "webapp:product_view" product.pk %}">{{ product.name }}</a></h5>
                        <p class="card-text">Категория: {{ product.get_category_display }}</p>
                        <p class="card-text">Осталось: {{ product.remainder }} по {{ product.price }} $</p>
                        <div class="btn-group">
                            {% if perms.webapp.change_product %}
                            <a class="btn btn-primary" href="{% url 'webapp:product_update' product.pk %}">Изменить</a>
                            {%  endif %}
                            {% if perms.webapp.delete_product %}
                            <a class="btn btn-danger" href="{% url 'webapp:product_delete' product.pk %}">Удалить</a>
                            {%  endif %}
                        </div>
                        {% include "partial/cart_add_form.html" %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/webapp/templates/products/product_create.html
{% extends 'base.html' %}

{% block nav %}{% endblock %}
{% block content %}
    <h1>Product Create</h1>

    <form method="post">
        {% include "partial/form.html" with button_text="Add" %}
    </form>

{% endblock %}

source/webapp/templates/products/product_delete.html
{% extends 'base.html' %}

{% block title %}Удаление{% endblock %}

{% block nav %}
    <li class="nav-item"><a class="nav-link" href="{% url 'webapp:product_view' product.pk %}">Отмена</a></li>
{% endblock %}

{% block content %}
    <h1>Вы уверены, что хотите удалить товар "{{ product.name }}" ({{ product.get_category_display }})?</h1>
    <form action="{% url "webapp:product_delete" product.pk %}" method="post">
        {% csrf_token %}
        <div class="btn-group">
            <button class="btn btn-danger" type="submit">Да</button>
            <a class="btn btn-primary" href="{% url 'webapp:product_view' product.pk %}">Отмена</a>
        </div>
    </form>
{% endblock %}

source/webapp/templates/products/product_update.html
{% extends 'base.html' %}

{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:product_view' product.pk %}">Return to Product</a>
    </li>
{% endblock %}
{% block content %}
    <h1>Update product</h1>

    <form method="post">
        {% include "partial/form.html" with button_text="Update" %}
    </form>

{% endblock %}

source/webapp/templates/products/product_view.html
{% extends 'base.html' %}

{% block nav %}
    {% if perms.webapp.change_product %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:product_update' product.pk %}">Update Product</a>
    </li>
    {% endif %}
    {% if perms.webapp.delete_product %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:product_delete' product.pk %}">Delete Product</a>
    </li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <h1>{{ product.name }}</h1>
            <p class="card-text">Категория: {{ product.get_category_display }}</p>
            <p class="card-text">Осталось: {{ product.remainder }} по {{ product.price }} $</p>
            <p class="pre">{{ product.description }}</p>
            <br>
            {% include "partial/cart_add_form.html" %}
        </div>
    </div>
    <a href="{% url 'webapp:index' %}">Return to list of products</a>
{% endblock %}